apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xs2d90226-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xs2d90226-java-springboot-gitops